#!/bin/sh

##
## Manual
##

outputHelp() {
  echo "SYNTAX"
  echo "  " $(basename ${BASH_SOURCE[0]}) "[-h] [-b BUCKET_NAME]"
  echo ""
  echo "DESCRIPTION"
  echo "  Generate an S3 Bucket Policy allowing access only to IP addresses listed in"
  echo "  IP_WHITELIST file"
  echo ""
  echo "OPTIONS"
  echo "  -b BUCKET_NAME    S3 Bucket name the policy is generated for"
  echo "  -h                Print this help and exit"
}

##
## Main
##

bucketName="vanmoof-beta-uikit"

while getopts "hb:" option; do
  case $option in
    h)
       outputHelp
       exit
    ;;
    b)
      bucketName=$OPTARG
    ;;
    ?)
      echo
      outputHelp
      exit 2
    ;;
  esac
done

scriptDir=$(dirname $0)

ipCSV=$(cat "$scriptDir/../IP_WHITELIST" \
  | grep -Ev "^#|^$" \
  | awk '{ print "\"" $1 "\""; }' \
  | paste -s -d ","
)

echo "{
	\"Version\": \"2012-10-17\",
	\"Id\": \"PolicyId2\",
	\"Statement\": [
		{
			\"Effect\": \"Allow\",
			\"Principal\": \"*\",
			\"Action\": [
				\"s3:GetObject\",
				\"s3:ListBucket\"
			],
			\"Resource\": [
				\"arn:aws:s3:::${bucketName}\",
				\"arn:aws:s3:::${bucketName}/*\"
			],
			\"Condition\": {
				\"IpAddress\": {
					\"aws:SourceIp\": [${ipCSV}]
				}
			}
		}
	]
}" > s3-policy.json
