#!/bin/sh -e

# Dont run when in CI environment.
# For ex. when pushing changelogs via "semantic-release".
if [ -n "$CI" ]; then
  exit 0
fi

# Remove comments from git commit message to not trigger [body-max-line-length]
sed '/^#/d' < "$1" \
  | npx --no-install commitlint
